config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'
  get "/email_processor", to: proc { [200, {}, ["OK"]] }, as: "mandrill_head_test_request"
  mount_griddler
	
  resources :subjects

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/email_processor.rb
class EmailProcessor
  
  def initialize(email)
    @email = email
  end

  def process
    a =  Subject.find_or_initialize_by(:subject => @email.subject, :to => @email.to[0][:email])
    
    if a.messages.count > 0
      a.messages.create(:message => @email.body)
    else
      a.save
      SlackerService.new.send_slack(a.id.to_s, @email.to[0][:email] , @email.subject).deliver
      a.messages.create(:message => @email.body)
    end
    a.save!
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :subject
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :subjects
end

app/models/slack.rb
class SlackerService
  require 'net/http'
  NAME_AND_ICON = {
      username: 'Exception Notifier',
      icon_emoji: ':bat:'
  }

  GOOD = 'good'
  WARNING = 'warning'
  DANGER = 'danger'

  def initialize(channel = ENV['SLACK_WEBHOOK_CHANNEL'])
    @uri = URI(ENV['SLACK_WEBHOOK_URL'])
    @channel = channel
  end

  def send_slack(link, application, title)
    params = {
        attachments: [
            {
                title: 'New Exception Reported',
                fallback: 'New Exception Reported',
                color: GOOD,
                fields: [
                    {
                        title: 'Link',
                        value: ENV['SITE_URL'] + "subjects/" + link,
                        short: true
                    },
                    {
                        title: 'Application',
                        value: application,
                        short: true
                    },
                    {
                        title: 'Title',
                        value: title,
                        short: false
                    }
                ]
            }
        ]
    }
    @params = generate_payload(params)
    self
  end

  def deliver
    begin
      Net::HTTP.post_form(@uri, @params)
    rescue => e
      Rails.logger.error("SlackerService: Error when sending: #{e.message}")
    end
  end

  private

  def generate_payload(params)
    {
        payload: NAME_AND_ICON
                     .merge(channel: @channel)
                     .merge(params).to_json
    }
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :project
  has_many :messages
  
  
  def hit_count
    self.messages.count rescue "0"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
    @subjects = Subject.all
    
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  before_filter :require_user_signed_in

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:subject, :from, :priority, :to, :project_id)
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/landings/index.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => Subject %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:subject) %></th>
      <th><%= model_class.human_attribute_name(:from) %></th>
      <th><%= model_class.human_attribute_name(:priority) %></th>
      <th><%= model_class.human_attribute_name(:to) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.id %></td>
        <td><%= subject.subject %></td>
        <td><%= subject.from %></td>
        <td><%= subject.priority %></td>
        <td><%= subject.to %></td>
        <td><%=l subject.created_at, format: :long %></td>
        <td>
          <%= link_to subject_path(subject), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to subject_path(subject), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_subject_path,
            :class => 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExceptionHandler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/subjects/_form.html.erb
<%= form_for @subject, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :subject, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :subject, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :from, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :from, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :priority, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :priority, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :to, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :to, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  subjects_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Subject %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subjects/new.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Subject %></h1>
</div>
<%= render :partial => 'form' %>

app/views/subjects/show.html.erb
<%- model_class = Subject -%>
<div class="page-header">
  <h1><%=t '.title', :default => Subject %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:subject) %></dt>
      <dd><pre class="prettyprint"><%= @subject.subject %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:from) %></dt>
      <dd><pre class="prettyprint"><%= @subject.from %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:priority) %></dt>
      <dd><pre class="prettyprint"><%= @subject.priority %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:to) %></dt>
      <dd><pre class="prettyprint"><%= @subject.to %></pre></dd>
  </dl>
</div>
<% @subject.messages.each do |a| %>
<div class="fieldset">
  <dl>
    <dt class="label label-default">Message Body</dt>
    <dd><pre class="prettyprint"><%= a.message rescue "none" %></pre></dd>
  </dl>
  <dl>
    <dt class="label label-default">Message date</dt>
    <dd><pre class="prettyprint"><%= a.created_at rescue "none" %></pre></dd>
  </dl>
</div>
<% end %>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              subjects_path, :class => 'btn btn-default'  %>
</div>